version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
